# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 327bf660e3ce87867f91614dd15be8c957a0f86368f0601314e87a772543246399a7e0de0450c09e8f0aba30ef7d2b32248e57d89977fad37939dbfff5a6fc76

test:
  secret_key_base: a9abb3f1cfabf7cc1fdd4300ba752a4c40e222585c3c7f36fbff58d4551ca93a10c8c0f3cb35e3e5f00ea876fd56e99c36c56c7e352aa40400af48d29e7ade76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
