# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8053b47b4ce543e5fe4f2cbe6d977799ce25a28a7f8e522c0f0fd4fff3665ea89f67e1a8f1ff5021be5ed2b91358919384d8fa5dfc74711e06137ef766242de

test:
  secret_key_base: 11aa74bd25e68f34210a5b1f68c99f3c8f9fb084fd5de818c7db3917208abb6b3a9af834d4eecdc2a7f81714d247c825bd37811cbae9506770a0b2c316db881d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
