# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9130c98e4c68cba9d2a6c0c4790f840354fe7b4d79f34d7b8bdbb4840c82ec2fd8abc7f473a57739e968cb61bca16c64e773e9c87cb79abc3b8c6978d898d9d9

test:
  secret_key_base: 6a46dc1d4ae7d60a7c22279d7fc5658d5fbaf47478231b59a93047229407741b93ee34c96fafd99307ae74d2795b5477223dcd4d0674d81333d1f9a6a7c0ba36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
